openapi: 3.0.0
x-stoplight:
  id: 8rmmut9xkw3te
info:
  title: Hermes-Prime-3.0
  version: '1.0'
  description: |-
    Handles the majority of what **Project Hermes** is capable of. For example, it provides endpoints that manage the CRUD operations for _Users_ and _Friends_, as well as an endpoint for _Check Ins_.

    A _Check In_ is an event where a User is generating a message to send to their Friend and all that work is done by this API.
  contact:
    name: Devin Leaman (4lch4)
    url: 'https://4lch4.link'
    email: hey@4lch4.email
  license:
    name: GPLv3
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: 'http://localhost:5050/api/v1'
    description: Local Testing
  - url: 'https://test.hermesapp.dev/api/v1'
    description: Test Environment
  - url: 'https://hermesapp.dev/api/v1'
    description: Production Environment
paths:
  /users:
    get:
      summary: Get Users
      tags:
        - Users
      responses:
        '200':
          description: Returns an array of User objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/User.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      operationId: getUsers
      description: |-
        _This endpoint is an Admin only endpoint. You can only access it if your API token has an `admin` level scope._

        Retrieve a list/array of all the Users currently stored in the DB.
    post:
      summary: Create User
      operationId: createUser
      responses:
        '200':
          description: The body of the User that was created.
          content:
            application/json:
              schema:
                $ref: ../models/User.yaml
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      description: Create a new User and store it in the DB.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/User_CREATE.yaml
        description: The object containing the Users properties.
      tags:
        - Users
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User
      tags:
        - Users
      responses:
        '200':
          description: The User with the given `userId`.
          content:
            application/json:
              schema:
                $ref: ../models/User.yaml
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      operationId: getUsers
      description: Get an existing User with the given `userId`.
      parameters: []
    patch:
      summary: Update User
      operationId: updateUser
      responses:
        '200':
          description: The latest version of the User object after the given properties were updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: User Not Found
        '500':
          description: Internal Server Error
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/User_UPDATE.yaml
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: An object containing the properties you wish to update.
      tags:
        - Users
    delete:
      summary: Delete User
      operationId: deleteUser
      responses:
        '200':
          description: The User object that was deleted.
          content:
            application/json:
              schema:
                $ref: ../models/User.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: User Not Found
        '500':
          description: Internal Server Error
      description: Delete an existing User with the given `userId`.
      tags:
        - Users
  /friends:
    get:
      summary: Get Friends
      tags:
        - Friends
      responses:
        '200':
          description: An array of Friend objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Friend.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      operationId: getFriends
      description: |-
        _This endpoint is an Admin only endpoint. You can only access it if your API token has an `admin` level scope._

        Retrieve a list/array of all the Friends currently stored in the DB.
    post:
      summary: Create Friend
      operationId: createFriend
      responses:
        '200':
          description: The body of the Friend that was created.
          content:
            application/json:
              schema:
                $ref: ../models/Friend.yaml
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      description: Create a new Friend and store it in the DB.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Friend_CREATE.yaml
        description: The body of the Friend to be created.
      tags:
        - Friends
  '/friends/{friendId}':
    parameters:
      - schema:
          type: string
        name: friendId
        in: path
        required: true
    get:
      summary: Get A Friend
      tags:
        - Friends
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Friend.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      operationId: getFriend
      description: Get a friend with the given `friendId`.
    patch:
      summary: Update Friend
      operationId: updateFriend
      responses:
        '200':
          description: Returns the latest version of the Friend object after the given properties were updated.
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Update a friend with the given `friendId`.
      tags:
        - Friends
    delete:
      summary: Delete Friend
      operationId: deleteFriend
      responses:
        '200':
          description: OK
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Delete a Friend with the given `friendId`.
      tags:
        - Friends
  /checkins:
    get:
      summary: Get All Check Ins
      tags:
        - CheckIns
      responses:
        '200':
          description: An array of CheckIn objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/CheckIn.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      operationId: getCheckIns
      description: |-
        _This endpoint is an Admin only endpoint. You can only access it if your API token has an `admin` level scope._

        Retrieve a list/array of all the Users currently stored in the DB.
    post:
      summary: Create Check In
      operationId: createCheckIn
      responses:
        '200':
          description: The created CheckIn object.
          content:
            application/json:
              schema:
                $ref: ../models/CheckIn.yaml
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '500':
          description: Internal Server Error
      description: Initiates the Check In process and stores an object in the DB for record of the event.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/CheckIn_CREATE.yaml
        description: An object containing the CheckIn properties.
      tags:
        - CheckIns
  '/checkins/{checkInId}':
    parameters:
      - schema:
          type: string
        name: checkInId
        in: path
        required: true
    get:
      summary: Get Check In
      tags:
        - CheckIns
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/CheckIn.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: CheckIn Not Found
        '500':
          description: Internal Server Error
      operationId: getCheckIn
      description: Get an existing Check In with the given `checkInId`.
    patch:
      summary: Update Check In
      operationId: updateCheckIn
      responses:
        '200':
          description: The latest version of the CheckIn object after the given properties were updated.
          content:
            application/json:
              schema:
                $ref: ../models/CheckIn.yaml
        '400':
          description: Bad Request
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Update an existing Check In with the given `checkInId`.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/CheckIn_UPDATE.yaml
        description: An object with the new properties/values to update.
      tags:
        - CheckIns
    delete:
      summary: Delete Check In
      operationId: deleteCheckIn
      responses:
        '200':
          description: The Check In object that was deleted.
          content:
            application/json:
              schema:
                $ref: ../models/CheckIn.yaml
        '401':
          description: No API token was provided.
        '403':
          description: Your API token doesn't have the necessary scope(s) to access this endpoint.
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Delete an existing Check In with the given `checkInId`.
      tags:
        - CheckIns
components:
  schemas: {}
  securitySchemes:
    Query API Key:
      name: apiKey
      type: apiKey
      in: query
security:
  - Query API Key: []
tags:
  - name: CheckIns
    description: Operations related to check ins CRUD.
  - name: Friends
    description: Operations related to Friends CRUD.
  - name: Users
    description: Operations related to Users CRUD.
